name: Build FullMoon iOS

on:
  push:
    branches: [ main ]
  workflow_dispatch: # Botão para executar manualmente

jobs:
  build:
    runs-on: macos-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '16.2.0'
        
    - name: Resolve Dependencies
      run: |
        xcodebuild -resolvePackageDependencies -project fullmoon.xcodeproj
        
    - name: Create ExportOptions.plist
      run: |
        cat > ExportOptions.plist << EOF
        <?xml version="1.0" encoding="UTF-8"?>
        <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
        <plist version="1.0">
        <dict>
            <key>method</key>
            <string>development</string>
            <key>teamID</key>
            <string>${{ secrets.TEAM_ID }}</string>
            <key>signingStyle</key>
            <string>automatic</string>
            <key>stripSwiftSymbols</key>
            <true/>
        </dict>
        </plist>
        EOF
        
    - name: Setup Keychain & Apple Login
      env:
        APPLE_ID: ${{ secrets.APPLE_ID }}
        APP_PASSWORD: ${{ secrets.APP_PASSWORD }}
      run: |
        # Criar keychain temporário
        security create-keychain -p "" build.keychain
        security default-keychain -s build.keychain
        security unlock-keychain -p "" build.keychain
        security set-keychain-settings -lut 21600 build.keychain
        
        # Configurar variáveis de ambiente para xcodebuild
        export FASTLANE_USER="$APPLE_ID"
        export FASTLANE_PASSWORD="$APP_PASSWORD"
        
    - name: Build & Archive
      env:
        APPLE_ID: ${{ secrets.APPLE_ID }}
        APP_PASSWORD: ${{ secrets.APP_PASSWORD }}
      run: |        
        xcodebuild \
          -project fullmoon.xcodeproj \
          -scheme fullmoon \
          -destination 'generic/platform=iOS' \
          -configuration Release \
          -archivePath fullmoon.xcarchive \
          CODE_SIGN_STYLE=Automatic \
          DEVELOPMENT_TEAM=${{ secrets.TEAM_ID }} \
          -allowProvisioningUpdates \
          -allowProvisioningDeviceRegistration \
          archive
          
    - name: Export IPA
      run: |
        xcodebuild \
          -exportArchive \
          -archivePath fullmoon.xcarchive \
          -exportPath ./output \
          -exportOptionsPlist ExportOptions.plist \
          -allowProvisioningUpdates
          
    - name: Upload IPA
      uses: actions/upload-artifact@v4
      with:
        name: FullMoon-iOS-${{ github.sha }}
        path: "./output/*.ipa"
        retention-days: 30
        
    - name: Show Success Message
      run: |
        echo "✅ IPA gerado com sucesso!"
        echo "📱 Baixe o artifact e instale com AltStore"
        ls -la ./output/
