name: Build FullMoon iOS

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: 'latest-stable'
        
    - name: Install iOS Platform
      run: |
        sudo xcode-select -s /Applications/Xcode.app/Contents/Developer
        xcodebuild -downloadPlatform iOS || true
        
    - name: Resolve Dependencies
      run: |
        xcodebuild -resolvePackageDependencies -project fullmoon.xcodeproj
        
    - name: Create ExportOptions.plist
      run: |
        cat > ExportOptions.plist << EOF
        <?xml version="1.0" encoding="UTF-8"?>
        <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
        <plist version="1.0">
        <dict>
            <key>method</key>
            <string>development</string>
            <key>teamID</key>
            <string>${{ secrets.TEAM_ID }}</string>
            <key>signingStyle</key>
            <string>automatic</string>
        </dict>
        </plist>
        EOF
        
    - name: Setup API Key
      run: |
        # Keychain
        security create-keychain -p "" build.keychain
        security default-keychain -s build.keychain
        security unlock-keychain -p "" build.keychain
        security set-keychain-settings -lut 21600 build.keychain
        
        # API Key file
        mkdir -p ~/private_keys
        echo "${{ secrets.ASC_PRIVATE_KEY }}" > ~/private_keys/AuthKey_${{ secrets.ASC_KEY_ID }}.p8
        
    - name: Build & Archive
      run: |
        # Bundle ID único
        BUNDLE_ID="com.github.$(echo $GITHUB_REPOSITORY | tr '[:upper:]' '[:lower:]' | tr '/' '.')"
        echo "Bundle ID: $BUNDLE_ID"
        
        xcodebuild \
          -project fullmoon.xcodeproj \
          -scheme fullmoon \
          -sdk iphoneos \
          -configuration Release \
          -archivePath fullmoon.xcarchive \
          CODE_SIGN_STYLE=Automatic \
          DEVELOPMENT_TEAM=${{ secrets.TEAM_ID }} \
          PRODUCT_BUNDLE_IDENTIFIER="$BUNDLE_ID" \
          SKIP_INSTALL=NO \
          ENABLE_APP_INTENTS_METADATA_EXTRACTION=NO \
          -authenticationKeyPath ~/private_keys/AuthKey_${{ secrets.ASC_KEY_ID }}.p8 \
          -authenticationKeyID ${{ secrets.ASC_KEY_ID }} \
          -authenticationKeyIssuerID ${{ secrets.ASC_ISSUER_ID }} \
          -allowProvisioningUpdates \
          archive
          
    - name: Export IPA
      run: |
        xcodebuild \
          -exportArchive \
          -archivePath fullmoon.xcarchive \
          -exportPath ./output \
          -exportOptionsPlist ExportOptions.plist \
          -authenticationKeyPath ~/private_keys/AuthKey_${{ secrets.ASC_KEY_ID }}.p8 \
          -authenticationKeyID ${{ secrets.ASC_KEY_ID }} \
          -authenticationKeyIssuerID ${{ secrets.ASC_ISSUER_ID }}
          
    - name: Upload IPA
      uses: actions/upload-artifact@v4
      with:
        name: FullMoon-${{ github.sha }}
        path: "./output/*.ipa"
        retention-days: 30
